// GENERATED by app_shots golden-scaffold. Do not edit — regenerated each run.
// Captures every shot at every mapped device size. Run from the app root:
//   flutter test app_shots/golden/capture_test.dart
// Requires Flutter >=3.27.
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

import 'status_bar.dart';
import 'harness/home_harness.dart' as home_harness;
import 'harness/stats_harness.dart' as stats_harness;

class _GoldenDevice {
  const _GoldenDevice(
      this.id, this.width, this.height, this.dpr, this.inset, this.platform);
  final String id;
  final double width;
  final double height;
  final double dpr;
  final double inset;
  final TargetPlatform platform;
}

const _devices = <_GoldenDevice>[
  _GoldenDevice('iphone_6_9', 1320, 2868, 3.0, 62.0, TargetPlatform.iOS),
  _GoldenDevice('iphone_6_5', 1284, 2778, 3.0, 47.0, TargetPlatform.iOS),
  _GoldenDevice('ipad_13', 2064, 2752, 2.0, 24.0, TargetPlatform.iOS),
  _GoldenDevice('android_phone', 1080, 1920, 3.0, 24.0, TargetPlatform.android),
];

class _Shot {
  const _Shot(this.id, this.deviceIds, this.style, this.theme, this.build,
      this.preCapture);
  final String id;
  final List<String> deviceIds;
  final ShotStatusBarStyle style;
  final ThemeData Function() theme;
  final Widget Function() build;
  final Future<void> Function(WidgetTester) preCapture;
}

final _shots = <_Shot>[
  _Shot('home', ['iphone_6_9', 'iphone_6_5', 'ipad_13', 'android_phone'], home_harness.statusBarStyle, home_harness.buildTheme, home_harness.buildShot, home_harness.preCapture),
  _Shot('stats', ['iphone_6_9', 'iphone_6_5'], stats_harness.statusBarStyle, stats_harness.buildTheme, stats_harness.buildShot, stats_harness.preCapture),
];

void main() {
  for (final shot in _shots) {
    for (final device
        in _devices.where((d) => shot.deviceIds.contains(d.id))) {
      testWidgets('capture ${shot.id} @ ${device.id}', (tester) async {
        // Real shadows in marketing captures (flutter_test stubs them by
        // default). Toggled per-test (not via setUpAll/tearDownAll):
        // flutter_test's _verifyInvariants() runs after every individual
        // test, not once after the whole suite, so a suite-scoped toggle
        // false-fails every test except the one active when tearDownAll
        // finally resets it.
        debugDisableShadows = false;
        debugDefaultTargetPlatformOverride = device.platform;
        // Everything that can throw (precacheImage, pumpAndSettle, toImage,
        // ...) lives in this try so the resets below always run in
        // `finally` — not via addTearDown: flutter_test's
        // _verifyInvariants() runs before addTearDown callbacks and asserts
        // these are back to defaults, so an addTearDown-based reset always
        // false-fails the test. A bare reset at the end of the try body has
        // the right timing but isn't exception-safe: any throw above it
        // skips the reset and false-fails every subsequent capture test too.
        try {
          tester.view.physicalSize = Size(device.width, device.height);
          tester.view.devicePixelRatio = device.dpr;
          addTearDown(tester.view.reset);

          final captureKey = GlobalKey();
          await tester.pumpWidget(RepaintBoundary(
            key: captureKey,
            child: AppShotsChrome(
              theme: shot.theme(),
              statusBarStyle: shot.style,
              statusBarInset: device.inset,
              isIos: device.platform == TargetPlatform.iOS,
              child: shot.build(),
            ),
          ));

          // Drain image decodes the fake test clock never completes.
          await tester.runAsync(() async {
            for (final element in find.byType(Image).evaluate()) {
              final widget = element.widget as Image;
              await precacheImage(widget.image, element);
            }
          });
          try {
            await tester.pumpAndSettle(const Duration(milliseconds: 100),
                EnginePhase.sendSemanticsUpdate, const Duration(seconds: 10));
          } on FlutterError {
            // Infinite animation: capture a fixed frame instead.
            await tester.pump(const Duration(milliseconds: 600));
            debugPrint('APP_SHOTS_WARNING pumpAndSettle timed out for '
                '${shot.id}@${device.id}; captured fixed 600ms frame');
          }
          await shot.preCapture(tester);
          await tester.pump();

          final boundary = captureKey.currentContext!.findRenderObject()!
              as RenderRepaintBoundary;
          await tester.runAsync(() async {
            final image = await boundary.toImage(pixelRatio: device.dpr);
            final bytes =
                await image.toByteData(format: ui.ImageByteFormat.png);
            final file = File('app_shots/screenshots/golden/${shot.id}/${device.id}.png');
            file.parent.createSync(recursive: true);
            file.writeAsBytesSync(bytes!.buffer.asUint8List());
          });
        } finally {
          debugDefaultTargetPlatformOverride = null;
          debugDisableShadows = true;
        }
      });
    }
  }
}
