// GENERATED by app_shots golden-scaffold. Do not edit — regenerated each run.
// Loads real fonts before any capture test runs: every directory under
// app_shots/golden/fonts/ is registered as one font family (directory name =
// family name, which must exactly match TextStyle.fontFamily).
// Requires Flutter >=3.27.
import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';


Future<void> testExecutable(FutureOr<void> Function() testMain) async {
  TestWidgetsFlutterBinding.ensureInitialized();
  await _loadAppShotsFonts();

  await testMain();
}

Future<void> _loadAppShotsFonts() async {
  // Material icon glyphs (Icons.add, etc.) come from the framework's own
  // bundled MaterialIcons font, which plain `flutter test` never loads —
  // without this, every icon renders as a tofu/missing-glyph box. This is
  // the same approach golden_toolkit historically used.
  try {
    final materialIcons = FontLoader('MaterialIcons')
      ..addFont(rootBundle.load('fonts/MaterialIcons-Regular.otf'));
    await materialIcons.load();
  } catch (e) {
    debugPrint('APP_SHOTS_WARNING: failed to load MaterialIcons font ($e); '
        'icon glyphs may render as tofu in this environment.');
  }

  final fontsDir = Directory('app_shots/golden/fonts');
  if (!fontsDir.existsSync()) return;
  for (final entry in fontsDir.listSync()..sort((a, b) => a.path.compareTo(b.path))) {
    if (entry is! Directory) continue;
    final family = entry.uri.pathSegments.lastWhere((s) => s.isNotEmpty);
    final loader = FontLoader(family);
    for (final file in entry.listSync().whereType<File>().toList()
      ..sort((a, b) => a.path.compareTo(b.path))) {
      if (file.path.endsWith('.ttf') || file.path.endsWith('.otf')) {
        final bytes = file.readAsBytesSync();
        loader.addFont(Future.value(ByteData.sublistView(bytes)));
      }
    }
    await loader.load();
  }
}
