// GENERATED by app_shots golden-scaffold. Do not edit — regenerated each run.
// Requires Flutter >=3.27.
import 'package:flutter/material.dart';

enum ShotStatusBarStyle { light, dark }

/// Wraps a shot's screen in app chrome: MaterialApp + the app's theme +
/// a reserved status-bar inset + a synthetic "9:41 / wifi / full battery"
/// status bar, so headless captures match normalized simulator captures.
class AppShotsChrome extends StatelessWidget {
  const AppShotsChrome({
    super.key,
    required this.child,
    required this.theme,
    required this.statusBarStyle,
    required this.statusBarInset,
    required this.isIos,
  });

  final Widget child;
  final ThemeData theme;
  final ShotStatusBarStyle statusBarStyle;
  final double statusBarInset;
  final bool isIos;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: theme,
      home: Builder(
        builder: (context) => Material(
          type: MaterialType.transparency,
          child: Stack(
            children: [
              MediaQuery(
                data: MediaQuery.of(context).copyWith(
                  padding: EdgeInsets.only(top: statusBarInset),
                  viewPadding: EdgeInsets.only(top: statusBarInset),
                ),
                child: child,
              ),
              if (statusBarInset > 0)
                Positioned(
                  top: 0,
                  left: 0,
                  right: 0,
                  height: statusBarInset,
                  child: AppShotsStatusBar(
                    style: statusBarStyle,
                    isIos: isIos,
                    inset: statusBarInset,
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Deterministic synthetic status bar. Glyphs are CustomPaint (no icon
/// fonts), so rendering is identical on every machine.
class AppShotsStatusBar extends StatelessWidget {
  const AppShotsStatusBar({
    super.key,
    required this.style,
    required this.isIos,
    required this.inset,
  });

  final ShotStatusBarStyle style;
  final bool isIos;
  final double inset;

  @override
  Widget build(BuildContext context) {
    final color = style == ShotStatusBarStyle.light
        ? Colors.white
        : const Color(0xDD000000);
    // Clock band: Dynamic Island iPhones center content in the upper ~54pt;
    // notch iPhones in ~32pt; small insets (iPad/Android) fill the band.
    final band = inset >= 59.0 ? 54.0 : (inset >= 44.0 ? 32.0 : inset);
    return Align(
      alignment: Alignment.topCenter,
      child: SizedBox(
        height: band,
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: isIos ? 28.0 : 12.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('9:41',
                style: TextStyle(
                  color: color,
                  fontSize: isIos ? 16.0 : 13.0,
                  fontWeight: FontWeight.w600,
                  letterSpacing: isIos ? -0.3 : 0,
                ),
              ),
              CustomPaint(
                size: const Size(68, 12),
                painter: _StatusGlyphsPainter(color),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _StatusGlyphsPainter extends CustomPainter {
  const _StatusGlyphsPainter(this.color);
  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    final fill = Paint()
      ..color = color
      ..style = PaintingStyle.fill;
    // Cellular: four ascending bars.
    for (var i = 0; i < 4; i++) {
      final h = 4.0 + i * 2.5;
      canvas.drawRRect(
        RRect.fromRectAndRadius(
          Rect.fromLTWH(i * 5.0, size.height - h, 3.5, h),
          const Radius.circular(1),
        ),
        fill,
      );
    }
    // Wifi: three arcs + dot.
    final stroke = Paint()
      ..color = color
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1.8
      ..strokeCap = StrokeCap.round;
    final c = Offset(32, size.height - 1.5);
    for (var i = 0; i < 3; i++) {
      final r = 2.5 + i * 3.2;
      canvas.drawArc(
        Rect.fromCircle(center: c, radius: r),
        -2.35619449, // -3π/4
        1.57079633, // π/2 sweep
        false,
        stroke,
      );
    }
    canvas.drawCircle(c, 1.4, fill);
    // Battery: outline + full charge + nub.
    final outline = Paint()
      ..color = color.withValues(alpha: 0.45)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1;
    canvas.drawRRect(
      RRect.fromRectAndRadius(
        Rect.fromLTWH(44, size.height - 11.5, 21, 11),
        const Radius.circular(2.5),
      ),
      outline,
    );
    canvas.drawRRect(
      RRect.fromRectAndRadius(
        Rect.fromLTWH(45.5, size.height - 10, 18, 8),
        const Radius.circular(1.5),
      ),
      fill,
    );
    canvas.drawRRect(
      RRect.fromRectAndRadius(
        Rect.fromLTWH(65.8, size.height - 7.5, 1.6, 3),
        const Radius.circular(1),
      ),
      fill,
    );
  }

  @override
  bool shouldRepaint(covariant _StatusGlyphsPainter old) => old.color != color;
}
