/// Templates for the golden capture harness suite emitted by `golden-scaffold`.
///
/// All templates are embedded `const` strings so the command works from
/// `dart run` without locating bundled files. Rendered files may import only
/// dart:*, flutter, flutter_test, the target app's package, and google_fonts
/// (when detected). Substitution goes through [renderFlow], which throws on
/// any leftover `{{...}}` token.
library;

import 'flow_template.dart';
import 'store_specs.dart';

/// status_bar.dart — verbatim (no tokens). Always regenerated.
const String kGoldenStatusBarFile = r'''
// GENERATED by app_shots golden-scaffold. Do not edit — regenerated each run.
// Requires Flutter >=3.27.
import 'package:flutter/material.dart';

enum ShotStatusBarStyle { light, dark }

/// Wraps a shot's screen in app chrome: MaterialApp + the app's theme +
/// a reserved status-bar inset + a synthetic "9:41 / wifi / full battery"
/// status bar, so headless captures match normalized simulator captures.
class AppShotsChrome extends StatelessWidget {
  const AppShotsChrome({
    super.key,
    required this.child,
    required this.theme,
    required this.statusBarStyle,
    required this.statusBarInset,
    required this.isIos,
  });

  final Widget child;
  final ThemeData theme;
  final ShotStatusBarStyle statusBarStyle;
  final double statusBarInset;
  final bool isIos;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: theme,
      home: Builder(
        builder: (context) => Material(
          type: MaterialType.transparency,
          child: Stack(
            children: [
              MediaQuery(
                data: MediaQuery.of(context).copyWith(
                  padding: EdgeInsets.only(top: statusBarInset),
                  viewPadding: EdgeInsets.only(top: statusBarInset),
                ),
                child: child,
              ),
              if (statusBarInset > 0)
                Positioned(
                  top: 0,
                  left: 0,
                  right: 0,
                  height: statusBarInset,
                  child: AppShotsStatusBar(
                    style: statusBarStyle,
                    isIos: isIos,
                    inset: statusBarInset,
                  ),
                ),
            ],
          ),
        ),
      ),
    );
  }
}

/// Deterministic synthetic status bar. Glyphs are CustomPaint (no icon
/// fonts), so rendering is identical on every machine.
class AppShotsStatusBar extends StatelessWidget {
  const AppShotsStatusBar({
    super.key,
    required this.style,
    required this.isIos,
    required this.inset,
  });

  final ShotStatusBarStyle style;
  final bool isIos;
  final double inset;

  @override
  Widget build(BuildContext context) {
    final color = style == ShotStatusBarStyle.light
        ? Colors.white
        : const Color(0xDD000000);
    // Clock band: Dynamic Island iPhones center content in the upper ~54pt;
    // notch iPhones in ~32pt; small insets (iPad/Android) fill the band.
    final band = inset >= 59.0 ? 54.0 : (inset >= 44.0 ? 32.0 : inset);
    return Align(
      alignment: Alignment.topCenter,
      child: SizedBox(
        height: band,
        child: Padding(
          padding: EdgeInsets.symmetric(horizontal: isIos ? 28.0 : 12.0),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text('9:41',
                style: TextStyle(
                  color: color,
                  fontSize: isIos ? 16.0 : 13.0,
                  fontWeight: FontWeight.w600,
                  letterSpacing: isIos ? -0.3 : 0,
                ),
              ),
              CustomPaint(
                size: const Size(68, 12),
                painter: _StatusGlyphsPainter(color),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _StatusGlyphsPainter extends CustomPainter {
  const _StatusGlyphsPainter(this.color);
  final Color color;

  @override
  void paint(Canvas canvas, Size size) {
    final fill = Paint()
      ..color = color
      ..style = PaintingStyle.fill;
    // Cellular: four ascending bars.
    for (var i = 0; i < 4; i++) {
      final h = 4.0 + i * 2.5;
      canvas.drawRRect(
        RRect.fromRectAndRadius(
          Rect.fromLTWH(i * 5.0, size.height - h, 3.5, h),
          const Radius.circular(1),
        ),
        fill,
      );
    }
    // Wifi: three arcs + dot.
    final stroke = Paint()
      ..color = color
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1.8
      ..strokeCap = StrokeCap.round;
    final c = Offset(32, size.height - 1.5);
    for (var i = 0; i < 3; i++) {
      final r = 2.5 + i * 3.2;
      canvas.drawArc(
        Rect.fromCircle(center: c, radius: r),
        -2.35619449, // -3π/4
        1.57079633, // π/2 sweep
        false,
        stroke,
      );
    }
    canvas.drawCircle(c, 1.4, fill);
    // Battery: outline + full charge + nub.
    final outline = Paint()
      ..color = color.withValues(alpha: 0.45)
      ..style = PaintingStyle.stroke
      ..strokeWidth = 1;
    canvas.drawRRect(
      RRect.fromRectAndRadius(
        Rect.fromLTWH(44, size.height - 11.5, 21, 11),
        const Radius.circular(2.5),
      ),
      outline,
    );
    canvas.drawRRect(
      RRect.fromRectAndRadius(
        Rect.fromLTWH(45.5, size.height - 10, 18, 8),
        const Radius.circular(1.5),
      ),
      fill,
    );
    canvas.drawRRect(
      RRect.fromRectAndRadius(
        Rect.fromLTWH(65.8, size.height - 7.5, 1.6, 3),
        const Radius.circular(1),
      ),
      fill,
    );
  }

  @override
  bool shouldRepaint(covariant _StatusGlyphsPainter old) => old.color != color;
}
''';

/// flutter_test_config.dart — tokens: GOLDEN_DIR, GOOGLE_FONTS_IMPORT,
/// GOOGLE_FONTS_CONFIG. Always regenerated.
const String kGoldenTestConfigTemplate = r'''
// GENERATED by app_shots golden-scaffold. Do not edit — regenerated each run.
// Loads real fonts before any capture test runs: every directory under
// {{GOLDEN_DIR}}/fonts/ is registered as one font family (directory name =
// family name, which must exactly match TextStyle.fontFamily).
// Requires Flutter >=3.27.
import 'dart:async';
import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
{{GOOGLE_FONTS_IMPORT}}

Future<void> testExecutable(FutureOr<void> Function() testMain) async {
  TestWidgetsFlutterBinding.ensureInitialized();
  await _loadAppShotsFonts();
{{GOOGLE_FONTS_CONFIG}}
  await testMain();
}

Future<void> _loadAppShotsFonts() async {
  // Material icon glyphs (Icons.add, etc.) come from the framework's own
  // bundled MaterialIcons font, which plain `flutter test` never loads —
  // without this, every icon renders as a tofu/missing-glyph box. This is
  // the same approach golden_toolkit historically used.
  try {
    final materialIcons = FontLoader('MaterialIcons')
      ..addFont(rootBundle.load('fonts/MaterialIcons-Regular.otf'));
    await materialIcons.load();
  } catch (e) {
    debugPrint('APP_SHOTS_WARNING: failed to load MaterialIcons font ($e); '
        'icon glyphs may render as tofu in this environment.');
  }

  final fontsDir = Directory('{{GOLDEN_DIR}}/fonts');
  if (!fontsDir.existsSync()) return;
  for (final entry in fontsDir.listSync()..sort((a, b) => a.path.compareTo(b.path))) {
    if (entry is! Directory) continue;
    final family = entry.uri.pathSegments.lastWhere((s) => s.isNotEmpty);
    final loader = FontLoader(family);
    for (final file in entry.listSync().whereType<File>().toList()
      ..sort((a, b) => a.path.compareTo(b.path))) {
      if (file.path.endsWith('.ttf') || file.path.endsWith('.otf')) {
        final bytes = file.readAsBytesSync();
        loader.addFont(Future.value(ByteData.sublistView(bytes)));
      }
    }
    await loader.load();
  }
}
''';

/// harness/<shot>_harness.dart — tokens: SHOT_ID, STATUS_BAR_STYLE.
/// Written ONCE; owned by the developer/agent afterwards.
const String kGoldenHarnessTemplate = r'''
// Harness for shot "{{SHOT_ID}}" — scaffolded by app_shots golden-scaffold.
// This file is written once and never overwritten: YOU own it.
//
// Fill the TODOs with the real screen widget wrapped in curated mocks.
// Mock data must be FIXED (no clocks, no network, no randomness) so captures
// are reproducible run-over-run. If the app relies on the platform default
// font, set an explicit fontFamily in buildTheme() and put the .ttf under
// ../fonts/<Family>/ (directory name = family name).
// Requires Flutter >=3.27.
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import '../status_bar.dart';
// TODO: import the real screen + any mock scaffolding, e.g.
// import 'package:your_app/screens/home_screen.dart';

/// Synthetic status bar style over this shot (light text for dark headers).
final ShotStatusBarStyle statusBarStyle = ShotStatusBarStyle.{{STATUS_BAR_STYLE}};

/// The app's REAL theme for this shot.
ThemeData buildTheme() => ThemeData.light(); // TODO: the app's real theme

/// The real screen widget in its curated, marketing-perfect state.
Widget buildShot() => const Placeholder(); // TODO: real screen with fixed mocks

/// Optional staging after settle, before capture (open a dropdown, switch a
/// tab, scroll). Leave empty when not needed.
Future<void> preCapture(WidgetTester tester) async {}
''';

/// Renders flutter_test_config.dart for the target app.
String renderGoldenTestConfig({
  required String goldenDir,
  required bool useGoogleFonts,
}) {
  return renderFlow(kGoldenTestConfigTemplate, {
    'GOLDEN_DIR': goldenDir,
    'GOOGLE_FONTS_IMPORT': useGoogleFonts
        ? "import 'package:google_fonts/google_fonts.dart';"
        : '',
    'GOOGLE_FONTS_CONFIG': useGoogleFonts
        ? '  // GoogleFonts.* app calls load through AssetManifest, not the\n'
            '  // app_shots FontLoader. Bundle direct-call fonts under\n'
            '  // google_fonts/ and include google_fonts/ in pubspec.yaml assets.\n'
            '  GoogleFonts.config.allowRuntimeFetching = false;'
        : '',
  });
}

/// Renders a write-once per-shot harness skeleton.
String renderGoldenHarness({
  required String shotId,
  String statusBarStyle = 'dark',
}) {
  return renderFlow(kGoldenHarnessTemplate, {
    'SHOT_ID': shotId,
    'STATUS_BAR_STYLE': statusBarStyle,
  });
}

/// capture_test.dart — tokens: HARNESS_IMPORTS, DEVICE_ENTRIES, SHOT_ENTRIES,
/// OUT_DIR. Always regenerated.
const String kGoldenCaptureTestTemplate = r'''
// GENERATED by app_shots golden-scaffold. Do not edit — regenerated each run.
// Captures each shot at every mapped device size. Run PER SHOT from the app
// root (see SKILL.md Step 4.5) — never the whole file at once:
//   flutter test {{SELF_PATH}} --plain-name "capture <shot-id>" --fail-fast --timeout 30s
// Requires Flutter >=3.27.
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:flutter_test/flutter_test.dart';

import 'status_bar.dart';
{{HARNESS_IMPORTS}}

class _GoldenDevice {
  const _GoldenDevice(
      this.id, this.width, this.height, this.dpr, this.inset, this.platform);
  final String id;
  final double width;
  final double height;
  final double dpr;
  final double inset;
  final TargetPlatform platform;
}

const _devices = <_GoldenDevice>[
{{DEVICE_ENTRIES}}
];

class _Shot {
  const _Shot(this.id, this.deviceIds, this.style, this.theme, this.build,
      this.preCapture);
  final String id;
  final List<String> deviceIds;
  final ShotStatusBarStyle style;
  final ThemeData Function() theme;
  final Widget Function() build;
  final Future<void> Function(WidgetTester) preCapture;
}

final _shots = <_Shot>[
{{SHOT_ENTRIES}}
];

void main() {
  for (final shot in _shots) {
    for (final device
        in _devices.where((d) => shot.deviceIds.contains(d.id))) {
      testWidgets('capture ${shot.id} @ ${device.id}', (tester) async {
        // Real shadows in marketing captures (flutter_test stubs them by
        // default). Toggled per-test (not via setUpAll/tearDownAll):
        // flutter_test's _verifyInvariants() runs after every individual
        // test, not once after the whole suite, so a suite-scoped toggle
        // false-fails every test except the one active when tearDownAll
        // finally resets it.
        debugDisableShadows = false;
        debugDefaultTargetPlatformOverride = device.platform;
        // Everything that can throw (precacheImage, pumpAndSettle, toImage,
        // ...) lives in this try so the resets below always run in
        // `finally` — not via addTearDown: flutter_test's
        // _verifyInvariants() runs before addTearDown callbacks and asserts
        // these are back to defaults, so an addTearDown-based reset always
        // false-fails the test. A bare reset at the end of the try body has
        // the right timing but isn't exception-safe: any throw above it
        // skips the reset and false-fails every subsequent capture test too.
        try {
          tester.view.physicalSize = Size(device.width, device.height);
          tester.view.devicePixelRatio = device.dpr;
          addTearDown(tester.view.reset);

          final captureKey = GlobalKey();
          await tester.pumpWidget(RepaintBoundary(
            key: captureKey,
            child: AppShotsChrome(
              theme: shot.theme(),
              statusBarStyle: shot.style,
              statusBarInset: device.inset,
              isIos: device.platform == TargetPlatform.iOS,
              child: shot.build(),
            ),
          ));

          // Drain image decodes the fake test clock never completes. Only
          // deterministic bundled providers are precached; File/Network/custom
          // providers can hang the real clock (no timeout), so they are skipped
          // (mock them as Image.memory/Image.asset). Each precache is
          // additionally timeout-guarded so even a bundled provider can't block.
          await tester.runAsync(() async {
            for (final element in find.byType(Image).evaluate()) {
              final provider = (element.widget as Image).image;
              if (provider is! AssetBundleImageProvider &&
                  provider is! MemoryImage) {
                debugPrint('APP_SHOTS_WARNING: skipped precache of non-bundled '
                    'image ($provider); mock it as Image.memory/Image.asset');
                continue;
              }
              try {
                await precacheImage(provider, element)
                    .timeout(const Duration(seconds: 5));
              } catch (e) {
                debugPrint('APP_SHOTS_WARNING: precache failed/timed out for '
                    '$provider ($e)');
              }
            }
          });
          try {
            await tester.pumpAndSettle(const Duration(milliseconds: 100),
                EnginePhase.sendSemanticsUpdate, const Duration(seconds: 10));
          } on FlutterError {
            // Infinite animation: capture a fixed frame instead.
            await tester.pump(const Duration(milliseconds: 600));
            debugPrint('APP_SHOTS_WARNING pumpAndSettle timed out for '
                '${shot.id}@${device.id}; captured fixed 600ms frame');
          }
          await shot.preCapture(tester);
          await tester.pump();

          final boundary = captureKey.currentContext!.findRenderObject()!
              as RenderRepaintBoundary;
          await tester.runAsync(() async {
            final image = await boundary.toImage(pixelRatio: device.dpr);
            final bytes =
                await image.toByteData(format: ui.ImageByteFormat.png);
            final file = File('{{OUT_DIR}}/${shot.id}/${device.id}.png');
            file.parent.createSync(recursive: true);
            file.writeAsBytesSync(bytes!.buffer.asUint8List());
          });
        } finally {
          debugDefaultTargetPlatformOverride = null;
          debugDisableShadows = true;
        }
      });
    }
  }
}
''';

/// Renders capture_test.dart. [shots] pairs each plan shot with its import
/// prefix and resolved device classes; [devices] is the deduplicated union of
/// capture targets used by at least one shot.
String renderGoldenCaptureTest({
  required List<({String id, String prefix, List<String> deviceClasses})> shots,
  required List<StoreTarget> devices,
  required String outDir,
  required String selfPath,
}) {
  final harnessImports = shots
      .map((s) => "import 'harness/${s.prefix}.dart' as ${s.prefix};")
      .join('\n');
  final deviceEntries = devices.map((t) {
    final c = t.capture!;
    final platform = c.isIos ? 'TargetPlatform.iOS' : 'TargetPlatform.android';
    return "  _GoldenDevice('${t.deviceClass}', ${t.width}, "
        '${t.height}, ${c.dpr}, ${c.statusBarInsetPt}, $platform),';
  }).join('\n');
  final shotEntries = shots.map((s) {
    final ids = s.deviceClasses.map((d) => "'$d'").join(', ');
    return "  _Shot('${s.id}', [$ids], ${s.prefix}.statusBarStyle, "
        '${s.prefix}.buildTheme, ${s.prefix}.buildShot, '
        '${s.prefix}.preCapture),';
  }).join('\n');
  return renderFlow(kGoldenCaptureTestTemplate, {
    'HARNESS_IMPORTS': harnessImports,
    'DEVICE_ENTRIES': deviceEntries,
    'SHOT_ENTRIES': shotEntries,
    'OUT_DIR': outDir,
    'SELF_PATH': selfPath,
  });
}
